version: '0.0.1'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
    ports:
      - "0.0.0.0:8000:8000"
    stdin_open: true
    tty: true
