version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ACCESS_KEY_ID: ${ACCESS_KEY_ID}
        SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
    environment:
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
